[project]
name = "palm-9000"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "black>=25.1.0",
    "isort>=6.0.1",
    "jupyter>=1.1.1",
    "langchain>=0.3.26",
    "langchain-huggingface>=0.3.0",
    "torch>=2.7.1",
    "transformers>=4.53.0",
]
